version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: repensar-postgres
    environment:
      POSTGRES_DB: repensar_db
      POSTGRES_USER: repensar
      POSTGRES_PASSWORD: repensar_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repensar -d repensar_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: repensar-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    build: .
    container_name: repensar-app
    environment:
      DATABASE_URL: postgresql://repensar:repensar_password@db:5432/repensar_db
      SECRET_KEY: development-secret-key-change-in-production
      DEBUG: "true"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data: